# Generated by Django 4.0 on 2023-02-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gbfs_href', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('location', models.JSONField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('stations', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
