# Generated by Django 4.0 on 2023-02-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='Company',
            field=models.JSONField(null=True),
        ),
    ]
