# Generated by Django 4.0 on 2023-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='countries_id',
            new_name='country',
        ),
    ]
