# Generated by Django 4.0 on 2023-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='inversion',
            field=models.CharField(max_length=10),
        ),
    ]
